#ifndef __GNC_TREE_MODEL_COMMODITY_H
#define __GNC_TREE_MODEL_COMMODITY_H
#include <gtk/gtk.h>
#include "gnc-tree-model.h"
#include "gnc-commodity.h"
G_BEGIN_DECLS
#define GNC_TYPE_TREE_MODEL_COMMODITY (gnc_tree_model_commodity_get_type ())
G_DECLARE_FINAL_TYPE (GncTreeModelCommodity, gnc_tree_model_commodity, GNC, TREE_MODEL_COMMODITY, GncTreeModel)
#define GNC_TREE_MODEL_COMMODITY_NAME "GncTreeModelCommodity"
#define GNC_TYPE_TREE_MODEL_COMMODITY_ROW (gnc_tree_model_commodity_row_get_type ())
G_DECLARE_FINAL_TYPE (GncTreeModelCommodityRow, gnc_tree_model_commodity_row, GNC, TREE_MODEL_COMMODITY_ROW, GObject)
typedef enum { GNC_TREE_MODEL_COMMODITY_ROW_NAMESPACE, GNC_TREE_MODEL_COMMODITY_ROW_COMMODITY } GncTreeModelCommodityRowKind;
typedef enum { GNC_TREE_MODEL_COMMODITY_COL_NAMESPACE, GNC_TREE_MODEL_COMMODITY_COL_MNEMONIC, GNC_TREE_MODEL_COMMODITY_COL_USER_SYMBOL, GNC_TREE_MODEL_COMMODITY_COL_FULLNAME, GNC_TREE_MODEL_COMMODITY_COL_PRINTNAME, GNC_TREE_MODEL_COMMODITY_COL_UNIQUE_NAME, GNC_TREE_MODEL_COMMODITY_COL_CUSIP, GNC_TREE_MODEL_COMMODITY_COL_FRACTION, GNC_TREE_MODEL_COMMODITY_COL_QUOTE_FLAG, GNC_TREE_MODEL_COMMODITY_COL_QUOTE_SOURCE, GNC_TREE_MODEL_COMMODITY_COL_QUOTE_TZ, GNC_TREE_MODEL_COMMODITY_COL_LAST_VISIBLE = GNC_TREE_MODEL_COMMODITY_COL_QUOTE_TZ } GncTreeModelCommodityColumn;
GncTreeModelCommodity *gnc_tree_model_commodity_new (QofBook *book, gnc_commodity_table *ct);
GListModel *gnc_tree_model_commodity_get_roots (GncTreeModelCommodity *model);
GListModel *gnc_tree_model_commodity_row_get_children (GncTreeModelCommodityRow *row);
GncTreeModelCommodityRowKind gnc_tree_model_commodity_row_get_kind (GncTreeModelCommodityRow *row);
gnc_commodity_namespace *gnc_tree_model_commodity_row_get_namespace (GncTreeModelCommodityRow *row);
gnc_commodity *gnc_tree_model_commodity_row_get_commodity (GncTreeModelCommodityRow *row);
const gchar *gnc_tree_model_commodity_row_get_id (GncTreeModelCommodityRow *row);
gchar *gnc_tree_model_commodity_row_get_string (GncTreeModelCommodityRow *row, GncTreeModelCommodityColumn column);
gboolean gnc_tree_model_commodity_row_get_boolean (GncTreeModelCommodityRow *row, GncTreeModelCommodityColumn column);
G_END_DECLS
#endif